# Generated by Django 3.0.2 on 2020-05-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckList',
        ),
    ]
