# Generated by Django 3.0.2 on 2020-05-13 03:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.IntegerField(default=1234, verbose_name='Codigo Empleado'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_base',
            field=models.BooleanField(default=False, verbose_name='Es Base'),
        ),
    ]
