# Generated by Django 3.0.3 on 2020-05-18 14:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='check_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 14, 59, 23, 577600, tzinfo=utc), verbose_name='Fecha Chequeo'),
        ),
    ]
