# Generated by Django 3.0.2 on 2020-05-21 01:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_auto_20200518_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='check_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 1, 42, 15, 81315, tzinfo=utc), verbose_name='Fecha Chequeo'),
        ),
    ]
