# Generated by Django 3.0.3 on 2020-07-01 22:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_auto_20200520_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='check_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 22, 24, 29, 138689, tzinfo=utc), verbose_name='Fecha Chequeo'),
        ),
    ]
