# Generated by Django 3.0.3 on 2020-07-01 23:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_auto_20200701_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='check_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 23, 6, 49, 959152, tzinfo=utc), verbose_name='Fecha Chequeo'),
        ),
    ]
