# Generated by Django 3.0.3 on 2020-07-01 23:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_auto_20200701_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='check_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 23, 21, 17, 474522, tzinfo=utc), verbose_name='Fecha Chequeo'),
        ),
    ]
